[package]
name = "free-proxy-list"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
futures = "0.3.8"
isocountry = "0.3.2"
reqwest = "0.11.0"
select = "0.6.0"

[dev-dependencies]
tokio = "1.0.1"
